<a href="https://colab.research.google.com/github/SalehinLab/RLhw2/blob/main/AI_Homework_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#library 
import numpy as np

#Amount of grid 
grid = []

while True:
    row = list(input('User’s input from keyboard> Row value: ')) #manually user’s input 
    ints = []

    for n in row:
        ints.append(int(n))
    grid.append(ints)

    if len(grid) == 9:
        break
    print(' The Row ' + str(len(grid)) + ' Complete')


def possible(x, y, n):
    for i in range(0, 9):
        if grid[i][x] == n and i != y: # Checks for number (n) in X columns
            return False

    for i in range(0, 9):
        if grid[y][i] == n and i != x: # Checks for number (n) in X columns
            return False

    x0 = (x // 3) * 3
    y0 = (y // 3) * 3
    for X in range(x0, x0 + 3):
        for Y in range(y0, y0 + 3):  # Checks for numbers in box(no matter the position, it finds the corner)
            if grid[Y][X] == n:
                return False    
    return True

def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1, 10):
                    if possible(x, y, n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))

solve()

User’s input from keyboard> Row value: 040000000
 The Row 1 Complete
User’s input from keyboard> Row value: 001034620
 The Row 2 Complete
User’s input from keyboard> Row value: 603000070
 The Row 3 Complete
User’s input from keyboard> Row value: 000483507
 The Row 4 Complete
User’s input from keyboard> Row value: 000050060
 The Row 5 Complete
User’s input from keyboard> Row value: 000009040
 The Row 6 Complete
User’s input from keyboard> Row value: 005000001
 The Row 7 Complete
User’s input from keyboard> Row value: 800547396
 The Row 8 Complete
User’s input from keyboard> Row value: 000021000
[[2 4 8 6 7 5 1 3 9]
 [7 5 1 9 3 4 6 2 8]
 [6 9 3 2 1 8 4 7 5]
 [9 2 6 4 8 3 5 1 7]
 [1 8 4 7 5 2 9 6 3]
 [5 3 7 1 6 9 8 4 2]
 [4 7 5 3 9 6 2 8 1]
 [8 1 2 5 4 7 3 9 6]
 [3 6 9 8 2 1 7 5 4]]
